# Generated by Django 4.1.4 on 2022-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='fee',
            field=models.CharField(default='not paid', max_length=10),
        ),
    ]
